stages:
  - build
  - deploy

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE backend
    - docker push $IMAGE
  only:
    - main

deploy:
  stage: deploy
  image: docker/compose:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - scp docker-compose.yml prometheus.yml alerts.yml alertmanager.yml $DEPLOY_HOST:$DEPLOY_PATH
    - ssh $DEPLOY_HOST "
        cd $DEPLOY_PATH &&
        docker-compose pull app &&
        docker-compose up -d
      "
  only:
    - main
