global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'jaskacatalba454@gmail.com'
  smtp_auth_username: 'jaskacatalba454@gmail.com'  # Corrected email address format
  smtp_auth_password: 'ikfr hpcr wbte grhp'  # Replace this with a more secure way of handling passwords for production

route:
  receiver: 'gmail'

receivers:
  - name: 'gmail'
    email_configs:
      - to: 'jaskacatalba454@gmail.com'
        send_resolved: true  # Send notifications even when alerts are resolved
