version: '3.8'

services:
  mysqldb:
    image: mariadb:10.5.28-focal
    container_name: my-db
    restart: always
    ports: ["13306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: my-db-management
    restart: always
    ports: ["18080:8080"]

  app:
    build:
      context: backend
    container_name: water-salinity-app
    restart: always
    ports: ["3000:5000"]
    environment:
      - PORT=5000
    depends_on:
      - mysqldb

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports: ["3000:3000"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports: ["9093:9093"]
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

volumes:
  db-data:

deploy:
  resources:
    limits:
      cpus: '0.5'
      memory: 512M
