global:
  scrape_interval: 15s  # Collect data every 15 seconds

scrape_configs:
  - job_name: 'water-salinity-app'
    metrics_path: /metrics  # Ensure your application exposes metrics at this endpoint
    static_configs:
      - targets: ['app:5000']  # Ensure this points to your application's running container (adjust 'app' if needed)

rule_files:
  - /etc/prometheus/alerts.yml  # Ensure the path to the alert rules is correct

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Ensure your Alertmanager service is accessible from Prometheus
